namespace HELP {
const char* HELP =
   "Help Doc for *\n"
   "===============================================================================\n"
   "\n"
   "Command `help`\n"
   "-------------------------------------------------------------------------------\n"
   "\n"
   "Want to get a usage for this programme or some command, use like this:\n"
   "\n"
   "   >>> help; after the semicolon there is comment\n"
   "   ||| Help Doc for *\n"
   "   ||| ...(this doc)\n"
   "\n"
   "If want to get usage about other command, use `help <command>`.\n"
   "\n"
   "Basic type\n"
   "-------------------------------------------------------------------------------\n"
   "\n"
   "### `MessageBook`\n"
   "\n"
   "You can use a keyword `list` to get the current `MessageBook`, this programme\n"
   "will show its value as a list if `person`.\n"
   "\n"
   "### `Person`\n"
   "\n"
   "Use keyword `new` to get a empty person, or if you know his/her hash ID, use\n"
   "like `[<hash-ID-string>]` to get it. For example:\n"
   "\n"
   "   >>> new\n"
   "     |  ┌-----| id: \'b81d80d9a7822507301ead965c748cc0\' |-------\n"
   "     |  | name: [invaild], sex: [invaild], telephone: [invaild], mail-numbe ...\n"
   "     |  | email: [invaild], qq-number: [invaild], location: [invaild]\n"
   "     |  └ classes: []\n"
   "  >>> [\'b81\']\n"
   "     |  ┌-----| id: \'b81d80d9a7822507301ead965c748cc0\' |-------\n"
   "     |  | name: [invaild], sex: [invaild], telephone: [invaild], mail-numbe ...\n"
   "     |  | email: [invaild], qq-number: [invaild], location: [invaild]\n"
   "     |  └ classes: []\n"
   "\n"
   "### `String`\n"
   "\n"
   "A string is include by two quotation marks, such as `\"this\"`, or like `\'this\'`\n"
   "\n"
   "Command `exit`\n"
   "-------------------------------------------------------------------------------\n"
   "\n"
   "Use command `exit` to exit this programme.\n"
   "\n"
   "\n"
   "\n"
   "\n"
   "\n"
   "\n"
   "-------------------------------------------------------------------------------\n"
   "\n"
   "Help is too long?\n"
   "\n"
   "There are index of all help\'s table: (use `help <index>` to get help of some\n"
   "topic)\n"
   "\n"
   "``` table\n"
   "type            exit            help            ...\n"
   "\n"
   "[subindex for type]:\n"
   "messagebook     person          string\n"
   "```\n"
   "\n"
;}